## Sea Surface Temperature (SST) anomalies

Sea surface temperature anomalies measure the difference in temperature with respect to average conditions of the ocean. So, a positive difference means the surface ocean is warmer than normal and a negative difference means it's cooler than normal.  

In the graph below, redder colors indicate a positive difference and bluer colors indicate a negative difference. Does this make sense based on our discussion of how temperature is distributed around the Earth?

![SST anomaly](https://www.ospo.noaa.gov/data/sst/anomaly/2019/anomnight.1.3.2019.gif)

We are going to calculate sea surface temperature anomalies for the SODA dataset today.  SODA or Simple Ocean Data Assimilation combines experimental measurements of the ocean with modelled data to map out ocean conditions across the globe. The oceans are huge (almost 70% of the Earth's surface is covered by oceans) so it very difficult to get oceanographic measurements of every inch of it. Scientists instead use models based on their understanding of what influences the oceans to fill in the gaps in their measurements. They can also use models to go back in time to look at what oceans might have been like in the past.

### Pseudocode
Here are the steps we need to take:
1. import file
1. save the necessary variables
1. find the mean temperature
1. find SST anomaly

#### Step 1: Import file

```
change directory

import netcdf4 module

read in and save dataset as a variable called 'data'

look at the names of the variables
```

In [2]:
import os 
os.getcwd()

'/Users/brownscholar/Desktop/BRIDGEUP_ClimateCoders/191126_sstanomaly_SODA'

In [3]:
os.chdir("/Users/brownscholar/Dropbox/BridgeUp_ClimateCoders/Data")

In [4]:
from netCDF4 import Dataset
data = Dataset('soda3.12.2_mn_ocean_reg_2017.nc')

In [5]:
data

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    CDI: Climate Data Interface version 1.9.2 (http://mpimet.mpg.de/cdi)
    Conventions: CF-1.4
    history: Fri Jun 07 08:15:53 2019: cdo splityear temp.nc temp2
Fri Jun 07 08:12:38 2019: cdo mergetime /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.12.2_mn_ocean_reg_2016.nc /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.12.2_mn_ocean_reg_2017.nc temp.nc
Thu Nov 29 15:21:12 2018: ncrcat /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.12.2_mn_ocean_reg_2016_01.nc /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.12.2_mn_ocean_reg_2016_02.nc /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.12.2_mn_ocean_reg_2016_03.nc /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.12.2_mn_ocean_reg_2016_04.nc /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.12.2_mn_ocean_reg_2016_05.nc /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.12.2_mn_ocean_reg_2016_06.nc /aosc/greenland/soda3.12.2/REGRIDED/ocean/soda3.

In [6]:
data.variables.keys()

odict_keys(['time', 'xt_ocean', 'yt_ocean', 'xu_ocean', 'yu_ocean', 'st_ocean', 'sw_ocean', 'temp', 'salt', 'wt', 'ssh', 'mlt', 'mlp', 'mls', 'net_heating', 'prho', 'u', 'v', 'taux', 'tauy'])

This is a description of what each of these variables are

In [7]:
for variable in data.variables:
    print(variable,': ',data.variables[variable].long_name)

time :  time
xt_ocean :  longitude
yt_ocean :  latitude
xu_ocean :  longitude
yu_ocean :  latitude
st_ocean :  tcell zstar depth
sw_ocean :  ucell zstar depth
temp :  Potential temperature
salt :  Practical Salinity
wt :  dia-surface velocity T-points
ssh :  effective sea level (eta_t + patm/(rho0*g)) on T cells
mlt :  mixed layer depth determined by temperature criteria
mlp :  Depth of potential density mixed layer
mls :  mixed layer depth determined by salinity criteria
net_heating :  surface ocean heat flux coming through coupler and mass transfer
prho :  potential density referenced to 0 dbar
u :  i-current
v :  j-current
taux :  i-directed wind stress forcing u-velocity
tauy :  j-directed wind stress forcing v-velocity


In [8]:
for variable in data.variables:
    print(variable,': ',data.variables[variable].shape)

time :  (12,)
xt_ocean :  (720,)
yt_ocean :  (330,)
xu_ocean :  (720,)
yu_ocean :  (330,)
st_ocean :  (50,)
sw_ocean :  (50,)
temp :  (12, 50, 330, 720)
salt :  (12, 50, 330, 720)
wt :  (12, 50, 330, 720)
ssh :  (12, 330, 720)
mlt :  (12, 330, 720)
mlp :  (12, 330, 720)
mls :  (12, 330, 720)
net_heating :  (12, 330, 720)
prho :  (12, 50, 330, 720)
u :  (12, 50, 330, 720)
v :  (12, 50, 330, 720)
taux :  (12, 330, 720)
tauy :  (12, 330, 720)


Use the code above to print out the shape of the variables. What do the dimensions of temp i.e temperature correspond to?

In [9]:
data.variables['xt_ocean'].shape

(720,)

In [10]:
for variables in data.variables:
    print(variables, ':')

time :
xt_ocean :
yt_ocean :
xu_ocean :
yu_ocean :
st_ocean :
sw_ocean :
temp :
salt :
wt :
ssh :
mlt :
mlp :
mls :
net_heating :
prho :
u :
v :
taux :
tauy :


#### Step 2: Save the required variables

```
save the variables temperature depends on i.e time, st_ocean, yt_ocean, xt_ocean

save temperature i.e temp
```

In [11]:
# Save latitude as variable 
latitude = data.variables['yt_ocean'][:]

# Save longitude as variable
longitude = data.variables['xt_ocean'][:]

#Save time as variable
time = data.variables['time'][:]

#Save depth as variable
depth = data.variables['st_ocean'][:]

# Save temperature as variable
temp = data.variables['temp'][:]

In [12]:
# Save temperature as variable

Print out the minimum and maximum of each variable. Do these values make sense?

In [13]:
import numpy as np

#You can use the min() and max() *method* to do this calculation.
A = np.array([1,2,3,4,5])
print('Example: ',A.min(),'\n')


Example:  1 



In [14]:
print(depth.min(),'\n')
print(depth.max(),'\n')

5.033549785614014 

5395.02294921875 



In [15]:
print(temp.min(),'\n')
print(temp.max(),'\n')

-1.9938582 

38.07777 



In [16]:
print(time.min(),'\n')
print(time.max(),'\n')

13530.041666666666 

13860.041666666666 



In [17]:
print(longitude.min(),'\n')
print(longitude.max(),'\n')

0.25 

359.75 



In [18]:
print(latitude.min(),'\n')
print(latitude.max(),'\n')

-74.75 

89.75 



Notice that time is measured in a different format as days from Jan 01, 1980. Sound familiar? We'll learn how to convert to a datetime format using the function in another session.

Draw out what the temp variable might look like.

#### Step 3: Find mean temperature 

*Hint*: Use https://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.mean.html

First, we need to decide what depth we would consider to be surface ocean? Call this variable z.

In [19]:
z = depth[depth <= 20]
print(z)

[ 5.03354979 15.10064983]


Then, let's do this step by step. 

1. Only obtain data for the first month. You should get a grid with a shape of (50, 330, 720) 

In [20]:
temp[0]

masked_array(
  data=[[[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [-1.7133582830429077, -1.7133338451385498, -1.7132887840270996,
          ..., -1.713502049446106, -1.7134593725204468,
          -1.7134010791778564],
         [-1.7146706581115723, -1.7147420644760132, -1.7147945165634155,
          ..., -1.714470624923706, -1.714550256729126,
          -1.7146133184432983],
         [-1.719269871711731, -1.7193185091018677, -1.7193660736083984,
          ..., -1.7191441059112549, -1.7191851139068604,
          -1.719224214553833]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [-1.7133210897445679, -1.7132916450500488, -1.7133280038833618,
          ..., -1.7135671377182007, -1.7134387493133545,
          -1.7133781909942627],
         [-1.7134846448898315, -1.713546872138977, -1.7135862112045288,
 

1. Identify the index for the first z m of the ocean
1. Save temperature for the top z m

In [29]:
depth < 20
#tells where depth is less than 20 (true = meets conditional)

masked_array(data=[ True,  True, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
             mask=False,
       fill_value=True)

In [22]:

temp_jan = temp[0,depth<20,:,:]

Average over all z m. You should get a grid that is 330 by 720.

In [23]:
temp_jan_mean = temp_jan.mean(axis = 0)
temp_jan_mean.shape

(330, 720)

Now, find the mean for the entire grid.

In [24]:
#average surface temperature for entire world
temp_jan_mean.mean()

14.015762457458468

#### But....

You can do this step all at once by just applying the mean function to your array of the first month down to a depth of z m. I just wanted to make sure you got the steps its taking.

In [25]:
temp_jan.mean(axis = 0).mean()

14.015762457458468

Now find the mean for all 12 months to a depth of z m.

In [31]:
temp_all = temp[:,depth<20,:,:]

In [32]:
temp_mean = temp.mean(axis = 0).mean()
print(temp_mean)

7.215776356378635


#### Step 3: Find SST anomaly

Remember:

SST anomaly = SST - average SST

In [33]:
print(temp[:,depth<20,:,:] - temp_mean)

[[[[-- -- -- ... -- -- --]
   [-- -- -- ... -- -- --]
   [-- -- -- ... -- -- --]
   ...
   [-8.929134368896484 -8.929110527038574 -8.929065704345703 ...
    -8.929278373718262 -8.929235458374023 -8.929177284240723]
   [-8.93044662475586 -8.93051815032959 -8.930570602416992 ...
    -8.93024730682373 -8.930326461791992 -8.930389404296875]
   [-8.935046195983887 -8.935094833374023 -8.935142517089844 ...
    -8.934920310974121 -8.934961318969727 -8.9350004196167]]

  [[-- -- -- ... -- -- --]
   [-- -- -- ... -- -- --]
   [-- -- -- ... -- -- --]
   ...
   [-8.929097175598145 -8.929067611694336 -8.929104804992676 ...
    -8.929343223571777 -8.929215431213379 -8.929154396057129]
   [-8.929261207580566 -8.929323196411133 -8.929362297058105 ...
    -8.929415702819824 -8.929340362548828 -8.92926025390625]
   [-8.935885429382324 -8.935938835144043 -8.935990333557129 ...
    -8.9357328414917 -8.935784339904785 -8.935832977294922]]]


 [[[-- -- -- ... -- -- --]
   [-- -- -- ... -- -- --]
   [-- -- 

## Challenge

Repeat these steps for sea surface salinity data ('salt')